# Build and test image on each commit

trigger:
  branches:
    include:
    - '*'

variables:
  WORK_DIR: $(System.DefaultWorkingDirectory)
  DOCKER_BUILDKIT: 1

stages:
- stage: BuildAndTest
  displayName: Build image and test code
  jobs:
  - job: BuildAndTestJob
    displayName: Build image and test code
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - checkout: self
    - script: docker build -t datacube-zarr-test -f docker/Dockerfile .
      displayName: 'Build test image'
    - script: docker run --rm -v $(WORK_DIR)/coverage:/opt/datacube_zarr/coverage datacube-zarr-test ./check-code.sh integration_tests/
      displayName: 'Run tests'
    - task: PublishCodeCoverageResults@1
      displayName: Publish coverage results
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(WORK_DIR)/coverage/cov.xml'
        reportDirectory: '$(WORK_DIR)/coverage/htmlcov'
        pathToSources: '$(WORK_DIR)'
